name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      SONAR_SCANNER_VERSION: 4.7.0.2747 # Find the latest version in the "Windows" link on this page:
                                        # https://docs.sonarcloud.io/advanced-setup/ci-based-analysis/sonarscanner-cli/
      SONAR_SERVER_URL: "https://sonarcloud.io"
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed
      COVERAGE_RESULTS: coverage_results # Directory where coverage results will be placed
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Set up msbuild
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Setup VSTest.console.exe # Needed to run tests and generate coverage
        uses: darenm/Setup-VSTest@v1
        
      - name: Run debug build
        run: |
          msbuild src/ise-cs-bayer-ci.sln /p:configuration=debug /t:rebuild /nodeReuse:false
      
      - name: Run tests with coverage
        run: >
          vstest.console.exe src\x64\Debug\cpp-unit-test.dll 
          /EnableCodeCoverage 
          /Collect:"Code Coverage;Format=Xml" 
          /ResultsDirectory:"${{ env.COVERAGE_RESULTS }}"        
